
@withSocialBar = true
@withAfterPostIntroduce = false
@withChat = false
@withDiscover = true
@withAutoSavedOnPaused = true
@withPostSuggestionToUser = false
@withNewLayoutMoment = true
@withMusicSharing = true
@withSectionMenu = true
@withSectionShare = true
@withPostTTS = false
@withWeChatSignatureServer = false
@withLocalBase64 = true
@withSuggestAlreadyRead = true
@withForcePopupSectionReview = false
@withSponserLinkAds = false
@isUSVersion = false
@withZhiFaCDN = false
@withServerImport = true
@withSlackReporter = false
@withSkypeWebReporter = true
@withShareStoryGroup = true
@withDirectDraftShow = true
@withMobileBackendUploading = false
@withStaticPosts = false
@withNewFilePath=true
@withLanguageSetting=false
@withImportToEdit=false
@signUpUserNameLength = 16
@withPostTitleMaxLength = 180      #byte
@withPostSubTitleMaxLength = 120   #byte
@withNeo4JInDynamicPostFriend = true
@withNeo4JInMoment = true
@withNeo4JInFollowPosts = true
@MQTT_TIME_DIFF = 0
# @withLoginTokenMax = 10
@CHECK_UPDATE = true # 强制更新和推荐更新启用标志
@withFromExample = true #故事贴样张